export const defaultTableData = [
  {
    key: '1',
    lesson: '1 пара\n09:00 - 10:20',
    day1: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day2: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day3: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day4: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day5: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day6: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
  },
  {
    key: '2',
    lesson: '2 пара\n10:30 - 11:50',
    day1: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day2: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day3: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day4: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day5: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day6: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
  },
  {
    key: '3',
    lesson: '3 пара\n12:00 - 13:20\n12:30 - 13:50',
    day1: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day2: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day3: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day4: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day5: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day6: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
  },
  {
    key: '4',
    lesson: '4 пара\n14:00 - 15:20',
    day1: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day2: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day3: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day4: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day5: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day6: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
  },
  {
    key: '5',
    lesson: '5 пара\n15:30 - 16:50',
    day1: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day2: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day3: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day4: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day5: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day6: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
  },
  {
    key: '6',
    lesson: '6 пара\n17:00 - 18:20',
    day1: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day2: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day3: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day4: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day5: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day6: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
  },
  {
    key: '7',
    lesson: '7 пара\n18:30 - 19:50',
    day1: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day2: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day3: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day4: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day5: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day6: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
  },
  {
    key: '8',
    lesson: '8 пара\n20:00 - 21:20',
    day1: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day2: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day3: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day4: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day5: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
    day6: {
      weekType0: '',
      weekType1: '',
      weekType2: '',
      weekType3: '',
    },
  },
]
